<footer>
		<div class='footer-top'>
			<div class='col-md-3 col-sm-6 footer-top-panel'>
				<div class='footer-top-panel-title'>
					<h4 style='font-weight:900;'>NEWS</h4>
				</div>
				<hr>
				<div class='footer-top-panel-content'>
				
				</div>
			</div>
			<!-- END COL -->

			<div class='col-md-3 col-sm-6 footer-top-panel'>
				<div class='footer-top-panel-title'>
					<h4 style='font-weight:900;'>LINKS</h4>
				</div>
				<hr>
				<div class='footer-top-panel-content'>
				
				</div>
			</div>	
			<!-- END COL -->

			<div class='col-md-6 footer-top-panel'>
				<div class='footer-top-panel-title'>
					<h4 style='font-weight:900;'>CONTACT US</h4>
				</div>
				<hr>
				<div class='col-md-6 col-sm-6 footer-top-panel-content'>
					<h4><strong>Melbourne Office:</strong></h4>
					Level 13, 350 Collins Street,</br>
					Melbourne Vic 3000</br>
					Australia</br>
					<strong>TEL:</strong></br>
					+61 3 9607 2915</br>
					<strong>EMAIL:</strong></br>
					info@firstguardiancapital.com</br>
				</div>
				<div class='col-md-6 col-sm-6 footer-top-panel-content'>
					<h4><strong>Beijing Office:</strong></h4>
					8th Floor, Tower 3, China Central Place,No.77 Jianguo Road, Chaoyang District,
					Beijing, China 100022</br>
					<strong>TEL:</strong></br>
					+86 132 4015 4511/br></br>
					<strong>EMAIL:</strong></br>
					beijing@firstguardiancapital.com</br></br>
				</div>
			</div>
			<!-- END COL -->

			
		</div>
		
		<div class='footer-buttom'>
			<h4 style='font-weight:900;'>&copy;
				FIRST GUARDIAN CAPITAL PTY LTD
			</h4>
		</div>
	</footer>