<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Page heads, including stylesheet, links and libs -->
	<?php 
		include_once 'inc/_head.inc';
	?>
	<!-- Style design for current page -->
	<style type="text/css">
	/* 2.Image showcase */
	div#index-bg-top{
		width:100%;
		height:500px;
		margin-top:110px;
		background-image:url(assets/img/bg/bg-1.jpg);
		background-position:center;
	    background-repeat: no repeat;
		/* opacity:0.6; */
		/* background-color:#000033; */
	}
	
	
	div.fund-section{
		max-width:1280px;;
		min-height:100px;
		margin:0 auto;
		padding-top:30px;
		margin-bottom:50px;
		
	}
	
	div.funds-category{
		min-height:100px;
		padding-top:10px;
		
	}

	ul.funds-filter{
		list-style-type:none;
	}
	
	li.filter{
		cursor:pointer;
		display:inline-block;
		width:auto;
		height:auto;
		margin-right:5px;
		padding:10px 15px;
		background-color:var(--fg-blue);
		color:var(--gen-white);
	}
	
	li.filter:hover{
		background-color:var(--gen-white);
		color:var(--fg-blue);
	}	
	
	
	@media(max-width:768px)
	{
		li.filter{
			margin-top:5px;
		}
	}
	
	#funds .mix{
		display: none;
	}
	
	div.fund-box{
		height:400px;
		padding-bottom:20px;
	}
	
	div.fund-box-each{
		background-color: white;
		padding:10px 10px;
	}
	
	
	h4.fund-title{
		height: 35px;
	}
	
	span.fund-description{
		display: inline-block;
		/*font-size: 16px;*/
		/*font-style:italic;*/
		margin: 0px 0;
		padding-top:10px;
	}
	

	</style>

</head>
<body>
	<!-- TOP NAV BAR -->
	<?php include_once 'inc/_navi-centered.inc'; ?>
	
	<!-- FUNDS -->
	<section class="wrapper-bg-white">
		
		<div class='fund-section'>
			<h2 style='margin:30px auto;'>OUR<strong> FUNDS</strong></h2>
			<!-- funds category -->
			<div class="row funds-category">
				<ul class='funds-filter'>
					<li class='filter' data-filter="all">ALL FUNDS</li>
					<li class='filter' data-filter=".income">INCOME FUNDS</li>
					<li class='filter' data-filter=".growth">GROWTH FUNDS</li>
					<li class='filter' data-filter=".property">PROPERTY FUNDS</li>
					<li class='filter' data-filter=".asian">ASIAN EQUITY</li>
				</ul>
			</div><!--- END ROW -->
			
			<!-- funds details -->
			<div class='funds row' id='funds'>
				
				<div class='col-md-4 col-sm-6 fund-box wow fadeInDown mix all income'>
					<div class='fund-box-each'>
						<h4 class='fund-title'><strong>Australian Food and Farming Loan Fund</strong></h4>
						<span class='fund-description'>Fixed return of 8% p.a. paid semi-annually and guaranteed by AFF.</span></br>
						<span class='fund-description'>The Fund is also entitled to an annual profit distribution of 30% of net profit generated by AFF. </span></br>
						<span class='fund-description'>AFF have secured contributed net equity of $10 million to capitalize AFF.</span></br>
						<span class='fund-description'>Minimum investment of $100,000, with a loan term of 3 years.</span></br>
						<span class='fund-description'>Investing in operating agricultural assets focused on beef and lamb production in Northern Victoria.</span></br>
						<span class='fund-description'>Managed by professional agricultural asset managers with a strong focus on operational risk management</span></br>
						</br>
					</div>
					<!-- <a class='btn btn-default overview-btn' href='#'>LEARN MORE</a> -->
				</div><!-- end column -->
			
				
				<div class='col-md-4 col-sm-6 fund-box wow fadeInDown mix all income'>
					<div class='fund-box-each'>
						<h4 class='fund-title'><strong>Secured Income Fund</strong></h4>
						<span class='fund-description'>Minimum investment of $50,000, with a minimum investment term of 12 months</span></br>
						<span class='fund-description'>First mortgage security, against Australian real property assets</span></br>
						<span class='fund-description'>Highly experienced credit team, ensuring all loans adhere to strict credit criteria</span></br>
						<span class='fund-description'>Loans amounts will be limited to no more than 75% value, as determined by independent valuation</span></br>
						</br>
					</div>
					<!-- <a class='btn btn-default overview-btn' href='#'>LEARN MORE</a> -->
				</div><!-- end column -->
				
				<div class='col-md-4 col-sm-6 fund-box wow fadeInDown mix all income property'>
					<div class='fund-box-each'>
						<h4 class='fund-title'><strong>Japanese Income Fund</strong></h4>
						<span class='fund-description'>Targets 8% p.a income return, paid monthly basis, plus potential for capital gain.</span></br>
						<span class='fund-description'>Minimum investment of $100,000, with a minimum investment term of 12 months.</span></br>
						<span class='fund-description'>The fund will invest directly in distressed property and Japanese Real Estate Investment Trusts.</span></br>
						<span class='fund-description'>Income streams derived from rental yields along with long-term capital growth. </span></br>
						<span class='fund-description'>Reliable and professional partners both involved in Japan and Australia.</span></br>
						</br>
					</div>
					<!-- <a class='btn btn-default overview-btn' href='#'>LEARN MORE</a> -->
				</div><!-- end column -->
				
				<div class='col-md-4 col-sm-6 fund-box wow fadeInDown mix all growth property'>
					<div class='fund-box-each'>
						<h4 class='fund-title'><strong>Low Density Real Estate Development Fund</strong></h4>
						<span class='fund-description'>Aims to provide a return that is reflective of exposure to the Australian Residential property development sector.</span></br>
						<span class='fund-description'>Minimum investment of $50,000, with quarterly withdrawals.</span></br>
						<span class='fund-description'>The Fund develops residential property projects in Australia, with a development term of under two years.</span></br>
						<span class='fund-description'>The Management Team have delivered over 20 completed townhouse and apartment projects. </span></br>
						<span class='fund-description'>Focuses on areas with strong population growth, and high clearance rates.</span></br>

						</br>
					</div>
					<!-- <a class='btn btn-default overview-btn' href='#'>LEARN MORE</a> -->
				</div><!-- end column -->
				
				<div class='col-md-4 col-sm-6 fund-box wow fadeInDown mix all growth asian'>
					<div class='fund-box-each'>
						<h4 class='fund-title'><strong>First Guardian Pan Asian Fund</strong></h4>
						<span class='fund-description'>Absolute Return focused, actively managed to generate positive returns in all market conditions.</span></br>
						<span class='fund-description'>Aims to generate attractive capital gains from country, sector and stock selection.</span></br>
						<span class='fund-description'>Minimum investment $100,000 with monthly redemptions permitted</span></br>
						<span class='fund-description'>Provides investors with professionally managed exposure to Asian growth markets.</span></br>
						</br>
					</div>
					<!-- <a class='btn btn-default overview-btn' href='#'>LEARN MORE</a> -->
				</div><!-- end column -->
				
			</div>
		</div>
	</section>
	
	<!-- FOOTER -->
	<?php
		include_once 'inc/_footer.inc';
	?>
	<script>
		//alert(121)
		$(document).ready(function(){
			$('#funds').mixItUp();
		});
	</script>


</body>

</html>
