
<!-- Business Overview part -->
<style>
/* profile */

.approach{
	font-size: 18px;
	font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; 
	/* text-align: justify; */
   	
}

</style>


<section class="wrapper-bg-light">
	<div class="row wrapper-content">
		<div class = 'col-md-12'>
			<h2>OUR <strong>Approach</strong></h2><br>
		
				<p class="approach">
				
					First Guardian Capital (FGC) has a well-established process for successfully listing companies on stock exchanges in Australia.
				</p>
				<p class="approach">
					FGC can act as Corporate Advisor to manage the entire process of listing and to facilitate the preparation of all relevant documents. Our focus is to formulate a persuasive investment proposition that will be attractive to investors both locally and globally. We work with clients to structure each offer such that it adheres to all listing requirements and accurately presents the opportunity to investors. FGC will arrange for independent legal review and financial audit, to ensure all the listing and regulatory requirements of the stock exchange and ASIC are fully met.
				</p>
				<p class="approach">
					FGC will manage the entire listing process; organise the resources necessary for successfully preparing marketing and finan- cial information, and will provide ongoing services after listing. FGC will fully review and advise on the business strategy and marketing plans, and develop the documents necessary for the prospectus to reflect the investment opportunity.
				</p>
			</div>
		</div>

	</div>
</section>