
<!-- Business Overview part -->
<style>
/* our corp-overview */

div.co-title{
	padding-top: 10px;
}


.corp-overview{
	font-size: 18px;

}
</style>


<section class="wrapper-bg-light">
	<div class="row wrapper-content">
		<div class = 'col-md-8 co-title'>
			<h2>BUSINESS <strong>OVERVIEW</strong></h2></br>
			
			<p class='corp-overview'>First Guardian works closely with investors and businesses alike, that are
			looking to achieve sustainable growth in the Asia Pacific region in order to
			enhance and maximise long-term value and wealth creation. We have
			consistently based our investment decisions on thorough research and sound
			risk management, assuming a long-term view, focusing on achieving
			responsible capital growth.</p></br>

			<p class='corp-overview'>Our mission is to enable our clients to achieve their financial objectives
			through superior investment returns and solutions. We do this through offering
			a compact, client-oriented range of responsible, actively-managed investment
			strategies, all underpinned by our proprietary process. Our product range
			includes equity funds, real asset investments, private equity and structured
			products. As we are a pure play asset manager, we do not have the distractions
			of offering other financial services such as banking or insurance. Investing and
			advising is our sole focus.</p></br>

			<p class='corp-overview'>We have a relationship-driven philosophy for working with our clients. By
			providing intelligent, relevant and ongoing support and advice we become
			their trusted advisor.</p></br>
		</div>
	</div>
</section>