
<!-- FOOTER STYLE -->

<style>
footer{
	width:100%;
	
}

.footer-top{
	width:100%;
	overflow:auto;
	margin:0 auto;
	color:var(--gen-dark);
	background-color:var(--gen-white);
	padding-bottom:20px;
}

.footer-top-panel{
	min-height:250px;
	margin-top: 20px;
}	

.footer-top-panel-title{
	text-align:left;
}

.footer-top-panel-content{
	padding-bottom: 30px;
	font-size:18px;
}

.footer-buttom{
	background-color:var(--gen-dark);
	color:#f9fdff;
	font-weight:900;
	overflow:auto;
	margin:0 auto;
	padding-top:20px;
	padding-bottom:20px;
	text-align:center;
	/* border-top:1px solid cyan; */
}

.footer-form-input{
	margin:8px 0px;
	padding-left: 0px;
	padding-right: 0px;
}


.footer-link{
	padding-left: 0px;
	text-align:left;
	font-size: 14px;
	color: var(--gen-dark);

}

button#sub_us{
	width: 100%;
	background-color: var(--gen-dark);
	color: var(--gen-white);
}

button#sub_us:hover{
	background-color: var(--gen-white);
	color: var(--gen-dark);
}

a.news{
	font-size:14px;
	color:var(--gen-dark);
	padding-left:10px;
	font-weight:400;
}

</style>




<!-- FOOTER HTML -->
<footer>
	<div class='footer-top'>
	
		
		
		
		<div class='col-md-3 col-sm-6 footer-top-panel'>
			<div class='footer-top-panel-title'>
				<h4 style='font-weight:900;'>NEWS</h4>
				<hr>
			</div>
			
			<div class='footer-top-panel-content'>
				<a class='news' href='http://www.abc.net.au/triplej/programs/hack/hack/7994590'>
					<!-- <i class="fa fa-file-text" style='margin-bottom:15px;'></i> -->
					Donald Trump is the next US President.
				</a></br>
			</div>
		</div>
		<!-- END COL -->

		<div class='col-md-3 col-sm-6 footer-top-panel'>
			<div class='footer-top-panel-title'>
				<h4 style='font-weight:900;'><strong>ABOUT</strong></h4>
				<hr>
			</div>
			<div class='footer-top-panel-content'>
					<ul class='footer-link'><a class='footer-link' href="what-we-do.php">What We Do</a></ul>
					<ul class='footer-link'><a class='footer-link' href="Who-we-are.php" >Who We Are</a></ul>
					<ul class='footer-link'><a class='footer-link' href="approach.php" >Our Apporach</a></ul>
					<ul class='footer-link'><a class='footer-link' href="contact.php" >Contact</a></ul>
			</div>
		</div>	
		
		<div class='col-md-3 col-sm-6 footer-top-panel'>
			<div class='footer-top-panel-title'>
				<h4 style='font-weight:900;'><strong>SUBSCRIBE</strong></h4>
				<hr>
			</div>
			
			<div class='footer-top-panel-content'>
				<form>
					<div class="col-sm-12 footer-form-input">
						<input type="text" class="form-control" placeholder="firstname" required>
					</div>
					<div class="col-sm-12 footer-form-input">
						<input type="text" class="form-control" placeholder="lastname" required>
					</div>
					
					<div class="col-sm-12 footer-form-input">
						<input type="email" class="form-control" placeholder="email" required>
					</div>
					<div class="col-sm-12 footer-form-input">
						<button class="btn btn-default" id='sub_us'>SUBSCRIBE NOW</button>
					</div>
				</form>
			</div>
		</div>	
		<!-- END COL -->

		<!-- END COL -->
		<div class='col-md-3 col-sm-6 footer-top-panel'>
			<div class='footer-top-panel-title'>
				<h4 style='font-weight:900;'>CONNECT</h4>
				<hr>
			</div>
			
			<div class='footer-top-panel-content'>
				<a href='#'><i class="fa fa-facebook-square fa-2x fa-color-blue" style='margin-bottom:15px;'></i></a>
				<a href='#'><i class="fa fa-google-plus-square fa-2x fa-color-blue" style='margin-bottom:15px;'></i></a>
				<a href='#'><i class="fa fa-linkedin-square fa-2x fa-color-blue" style='margin-bottom:15px;'></i></a>
				<a href='#'><i class="fa fa-twitter-square fa-2x fa-color-blue" style='margin-bottom:15px;'></i></a>
				</br>
			</div>
		</div>	

		<!-- END COL -->
		

		<!-- <div class='col-md-6 footer-top-panel'>
			<div class='footer-top-panel-title'>
				<h4 style='font-weight:900;'>CONTACT US</h4>
			</div>
			<hr>
			<div class='col-md-6 col-sm-6 footer-top-panel-content'>
				<h4><strong>Melbourne Office:</strong></h4>
				Level 13, 350 Collins Street,</br>
				Melbourne Vic 3000</br>
				Australia</br>
				<strong>TEL:</strong></br>
				+61 3 9607 2915</br>
				<strong>EMAIL:</strong></br>
				info@firstguardiancapital.com</br>
			</div>
			<div class='col-md-6 col-sm-6 footer-top-panel-content'>
				<h4><strong>Beijing Office:</strong></h4>
				8th Floor, Tower 3, China Central Place,No.77 Jianguo Road, Chaoyang District,
				Beijing, China 100022</br>
				<strong>TEL:</strong></br>
				+86 132 4015 4511/br></br>
				<strong>EMAIL:</strong></br>
				beijing@firstguardiancapital.com</br></br>
			</div>
		</div> -->
		<!-- END COL -->

		
	</div>
	<!-- separate line 
	<hr style="max-width:1280px; margin-bottom: 0px;">-->

	<div class='footer-buttom'>
		<h4 style='font-weight:900;'>&copy;
			FIRST GUARDIAN CAPITAL PTY LTD
		</h4>
	</div>
</footer>

<script src="assets/js/scripts.js"></script>