
<!-- Business Overview part -->
<style>
/* profile */

div.profile{
	margin-top: 30px;
	margin-bottom: 80px;
	padding-bottom: 20px;
}

img.img-responsive{
	margin-bottom: 15px;
}

.profile-name{
	font-size: 24px;
	font-weight: 600;
	margin-top: -5px;

}

.profile-subs{
	font-size: 18px;
}

.profile-body{
	font-size: 16px;

}

.profile-name, .profile-subs, .profile-body{
	padding-left: 0;
	padding-right: 0;
}


.team{
	font-size: 18px;
	font-weight: 300;
}
</style>


<section class="wrapper-bg-white">
	<div class="row wrapper-content">
		<div class = 'col-md-12'>
			<h2>OUR <strong>TEAM</strong></h2></br>
		</div>
		<!-- END OF TITLE -->
		<div class='col-sm-12  profile'>
			<div class='col-md-4 col-sm-4'>
				<img class='img-responsive' src='assets/img/team-photos/da_s.jpg'>
			</div>
			<div class='col-md-8 col-sm-8'>
				<p class='profile-name col-md-12 col-sm-12'>
					<strong>DAVID ANDERSON</strong>
				</p>

				<p class='profile-subs col-md-12 col-sm-12'>
					<strong>CEO</strong>
				</p>

				<p class='profile-subs col-md-12 col-sm-12'>
					B.Com (Melb), Dip SIA, M.App.Fin
				</p>


				<p class='team' col-md-12 col-sm-12'>
					David is a co-founder of First Guardian Capital. He
					brings over 15 years of Investment Management
					and commercial experience to the firm. He is jointly
					responsible for the management of First Guardian’s in-
					vestment portfolios, and is responsible for implement-
					ing the Firm’s business strategy across Australia and
					Asia. As a fluent speaker of Mandarin Chinese and
					Indonesian, David has established strong business
					links across the Asian region, covering corporate
					advisory, capital raising and managing equity and
					direct asset portfolios for global investors.
				</p>

				<p class='team' col-md-12 col-sm-12'>
					Prior to establishing First Guardian Group, David gained
					extensive experience within top tier global
					investment managers. David managed equities at
					UBS Global Asset Management, where he worked for
					7 years, holding roles focused on research and in-
					vestment management. David also spent 5 years at
					Goldman Sachs JBWere Asset Management, working
					primarily as a Senior Investment Analyst.
				</p>
			</div>
		</div>
		<!-- END OF EACH PROFILE -->

		<div class='col-sm-12  profile'>
			<div class='col-md-4 col-sm-4'>
				<img class='img-responsive' src='assets/img/team-photos/simon.png'>
			</div>
			<div class='col-md-8 col-sm-8'>
				<p class='profile-name col-md-12 col-sm-12'>
					<strong>SIMON SELIMAJ</strong>
				</p>

				<p class='profile-subs col-md-12 col-sm-12'>
					<strong>Chief Investment Officer</strong>
				</p>

				<p class='profile-subs col-md-12 col-sm-12'>
					B.Bus, Dip SIA, Dip BA, ISFA
				</p>


				<p class='team' col-md-12 col-sm-12'>
					Simon is a co-founder and Director of First Guardian
					Capital, and is the Chief Investment Officer. Simon has
					over twenty years’ fund management experience as
					a portfolio manager and five years’ experience as an
					investment analyst. He has specialised skills in equities
					research, ethical and socially responsible investment,
					and macroeconomic analysis.
				</p>

				<p class='team' col-md-12 col-sm-12'>
					Simon has developed the First Guardian Capital’s
					Multi-Strategy Investment Matrix model which we
					apply across all our investment strategies. Simon’s ex-
					tensive experience as a portfolio manager was gained
					initially at Trust Company and Colonial Mutual. While
					at Colonial, Simon managed global equities portfolios
					for institutional clients. Simon was also an Investment
					Manager at one of Asia’s largest hedge funds, based in
					Tokyo, managing portfolios of over $7 billion across the
					Asia Pacific region.
				</p>
			</div>
		</div>
		<!-- END OF EACH PROFILE -->

		<div class='col-sm-12  profile'>
			<div class='col-md-4 col-sm-4'>
				<img class='img-responsive' src='assets/img/team-photos/craig.jpg'>
			</div>
			<div class='col-md-8 col-sm-8'>
				<p class='profile-name col-md-12 col-sm-12'>
					<strong>CRAIG MACKIESON</strong>
				</p>

				<p class='profile-subs col-md-12 col-sm-12'>
					<strong>Executive Director</strong>
				</p>

				<p class='profile-subs col-md-12 col-sm-12'>
					B.Sc (Melb), PGDipFin (Melb), GradDip AppFin (SIA)
				</p>


				<p class='team' col-md-12 col-sm-12'>
					Craig has over 14 years of investment banking and
					corporate finance experience across corporate advisory,
					valuations, project and structured finance, principal
					finance, mergers and acquisitions and has worked on
					a geographically-diverse range of transactions. He has
					extensive experience in corporate finance and
					valuations.
				</p>

				<p class='team' col-md-12 col-sm-12'>
					Craig has also worked at ANZ Investment Bank, Societe
					Generale Corporate and Investment Bank, and KPMG
					Corporate Finance.
				</p>
			</div>
		</div>
		<!-- END OF EACH PROFILE -->

	</div>
</section>