
<!-- SERVICES DETAILS -->

<style type="text/css">

/* Panel for each service introduce */
div.service-panel-row{
	max-width:1080px;
	margin:30px auto;
	padding-bottom:30px;
	border-bottom:2px solid var(--light-dark);
}

div.service-name{
	max-width:300px;
	text-align:center;
	margin:0 auto;
	font-size:24px;
	text-transform:uppercase;
}

div.service-intro{
	max-width:980px;
	font-size:18px;
	text-indent:30px;
	margin:0 auto;
}
</style>


<section class="wrapper-bg-white">
	<div class='service-panel-row'>
		<div class='service-name'>
			<i class="fa fa-bar-chart fa-2x fa-color-blue" style='margin-bottom:15px;'></i>
			<p>ASSET MANAGEMENT</p>
		</div>
		<div class='service-intro'>
			<p>Our core competencies include absolute return investment strategies, multi-asset portfolios, 
			strategic asset allocation, and risk management. We apply a flexible, all-weather investment style, which
			consistently adds value over time, independent of market conditions.</p>
		</div>
	</div>
	<!-- END OF ROW -->
	
		
	<div class='service-panel-row'>
		<div class='service-name'>
			<i class="fa fa-area-chart fa-2x fa-color-blue" style='margin-bottom:15px;'></i>
			<p>SUPERANNUATION</p>
		</div>
		<div class='service-intro'>
			<p>First Guardian Capital owns and operates an innovative, specialist superannuation (pension) fund, 
			First Guardian Super. The Fund is specifically designed and managed to meet the needs of Australia’s socially conscious community with an 
			appetite for responsible investing. The Fund enables investors to grow their superannuation whilst contributing to positive, sustainable change,			
			across society and the environment.
			</p>
		</div>
	</div>
	<!-- END OF ROW -->
	
	<div class='service-panel-row'>
		<div class='service-name'>
			<i class="fa fa-edit fa-2x fa-color-blue" style='margin-bottom:15px;'></i>
			<p>Corporate Finance</p>
		</div>
		<div class='service-intro'>
			<p>Our corporate advisory team performs an end-to-end role managing all aspects of our clients' corporate and debt structuring requirements.
			Our capabilities include analysis of operations and trading, risk
			assessment, identification of appropriate funding mechanisms, debt
			structuring and capital raising, negotiation of financing terms, management of financial closure, and post-drawdown project management.
			</p>
		</div>
	</div>
	<!-- END OF ROW -->
	
	<div class='service-panel-row'>
		<div class='service-name'>
			<i class="fa fa-pie-chart fa-2x fa-color-blue" style='margin-bottom:15px;'></i>
			<p>INVESTMENT BANKING</p>
		</div>
		<div class='service-intro'>
			<p>FGC can act as Corporate Advisor to manage the entire process of listing and to facilitate the preparation 
			of all relevant documents. Our focus is to formulate a persuasive investment proposition that will be attractive 
			to investors both locally and globally. We work with clients to structure each offer such that it adheres to all 
			listing requirements and accurately presents the opportunity to investors. FGC will arrange for independent legal 
			review and financial audit, to ensure all the listing and regulatory requirements of the stock exchange and ASIC are fully met.
			</p>
			<p>
			FGC will manage the entire listing process; organise the resources necessary for successfully preparing marketing 
			and finan- cial information, and will provide ongoing services after listing. FGC will fully review and advise on 
			the business strategy and marketing plans, and develop the documents necessary for the prospectus to reflect the investment opportunity.
			</p>
		</div>
	</div>
	<!-- END OF ROW -->
	
	<div class='service-panel-row'>
		<div class='service-name'>
			<i class="fa fa-line-chart fa-2x fa-color-blue" style='margin-bottom:15px;'></i>
			<p>Capital Raising</p>
		</div>
		<div class='service-intro'>
			<p>Drawing on our established network of investment partners across Asia, First Guardian Capital is
			uniquely placed to assist corporate clients with capital-raising, from private markets. With branch offices in Beijing and Shanghai, 
			we maintain a broad base of investment resources, 
			assisting clients to engage with qualified institutional and private investors, focused on offshore opportunities.
			</p>
		</div>
	</div>
	<!-- END OF ROW -->
	
	<div class='service-panel-row'>
		<div class='service-name'>
			<i class="fa fa-cog fa-2x fa-color-blue" style='margin-bottom:15px;'></i>
			<p>PLATFORM SOLUTIONS</p>
		</div>
		<div class='service-intro'>
			<p>Our corporate advisory team performs an end-to-end role managing all aspects of our clients' corporate and debt structuring requirements. Our capabilities include analysis of operations and trading, risk
			assessment and valuation, identification of appropriate funding mechanisms and venues, debt
			structuring and capital raising, negotiation of financing terms, management of financial closure, and post-drawdown project management.
			</p>
		</div>
	</div>
	<!-- END OF ROW -->

	
		
</section>