
<!-- SERVICES DETAILS -->

<style type="text/css">

/* Panel for each service introduce */
div.service-panel-row{
	max-width:1080px;
	margin:30px auto;
	padding-bottom:30px;
	border-bottom:2px solid var(--light-dark);
}

div.service-name{
	max-width:300px;
	text-align:center;
	margin:0 auto;
	font-size:24px;
	text-transform:uppercase;
}

div.service-intro{
	max-width:980px;
	font-size:18px;
	text-indent:30px;
	margin:0 auto;
}
</style>


<section class="wrapper-bg-white">
	<div class='service-panel-row'>
		<div class='service-name'>
			<i class="fa fa-bar-chart fa-2x fa-color-blue" style='margin-bottom:15px;'></i>
			<p>ASSET MANAGEMENT</p>
		</div>
		<div class='service-intro'>
			<p>Our core competencies include absolute return investment strategies, multi-asset portfolios, 
			strategic asset allocation, and risk management. We apply a flexible, all-weather investment style, which
			consistently adds value over time, independent of market conditions.</p>
		</div>
	</div>
	<!-- END OF ROW -->
	
		
	<div class='service-panel-row'>
		<div class='service-name'>
			<i class="fa fa-area-chart fa-2x fa-color-blue" style='margin-bottom:15px;'></i>
			<p>SUPERANNUATION</p>
		</div>
		<div class='service-intro'>
			<p>First Guardian Capital owns and operates an innovative, specialist superannuation (pension) fund, 
			First Guardian Super. The Fund is specifically designed and managed to meet the needs of Australia’s socially conscious community with an 
			appetite for responsible investing. The Fund enables investors to grow their superannuation whilst contributing to positive, sustainable change, 
			across society and the environment.
			</p>
		</div>
	</div>
	<!-- END OF ROW -->
	
	<div class='service-panel-row'>
		<div class='service-name'>
			<i class="fa fa-edit fa-2x fa-color-blue" style='margin-bottom:15px;'></i>
			<p>Corporate Advisory</p>
		</div>
		<div class='service-intro'>
			<p>Our corporate advisory team performs an end-to-end role managing all aspects of our clients' corporate and debt structuring requirements. Our capabilities include analysis of operations and trading, risk
			assessment and valuation, identification of appropriate funding mechanisms and venues, debt
			structuring and capital raising, negotiation of financing terms, management of financial closure, and post-drawdown project management.
			</p>
		</div>
	</div>
	<!-- END OF ROW -->
	
	<div class='service-panel-row'>
		<div class='service-name'>
			<i class="fa fa-pie-chart fa-2x fa-color-blue" style='margin-bottom:15px;'></i>
			<p>INVESTMENT STRATEGY</p>
		</div>
		<div class='service-intro'>
			<p>Our investment advice centres on your needs. We want to understand your personal circumstances and goals.
			We believe it is essential for our relationship to be based on trust and to be focused on finding investment solutions that are tailored to your personal circumstances and financial position. Our
			specialist team provides a comprehensive range of investment advisory services, 
			whilst benefiting from our expertise in asset management and investment banking.
			</p>
		</div>
	</div>
	<!-- END OF ROW -->
	
	<div class='service-panel-row'>
		<div class='service-name'>
			<i class="fa fa-line-chart fa-2x fa-color-blue" style='margin-bottom:15px;'></i>
			<p>Capital Raising</p>
		</div>
		<div class='service-intro'>
			<p>Drawing on our established network of investment partners across Asia, First Guardian Capital is
			uniquely placed to assist corporate clients with capital-raising, from private markets. With branch offices in Beijing and Shanghai, 
			we maintain a broad base of investment resources, 
			assisting clients to engage with qualified institutional and private investors, focused on offshore opportunities.
			</p>
		</div>
	</div>
	<!-- END OF ROW -->
	
	<div class='service-panel-row'>
		<div class='service-name'>
			<i class="fa fa-cog fa-2x fa-color-blue" style='margin-bottom:15px;'></i>
			<p>PLAFORM SOLUTIONS</p>
		</div>
		<div class='service-intro'>
			<p>Our corporate advisory team performs an end-to-end role managing all aspects of our clients' corporate and debt structuring requirements. Our capabilities include analysis of operations and trading, risk
			assessment and valuation, identification of appropriate funding mechanisms and venues, debt
			structuring and capital raising, negotiation of financing terms, management of financial closure, and post-drawdown project management.
			</p>
		</div>
	</div>
	<!-- END OF ROW -->

	
		
</section>